### ISSUE TITLE
FaceBOT TO-DO

### ISSUE THREAD

**Issue by facebotgit** [facebotgit/version#1]
- [x] Validação de licença
- [x] Geração de licença e registro de usuário (admin)
- [x] Bloqueamento de usuário (admin)
- [x] Installer
- [x] Updater
  - [x] Buscar versão mais recente
  - [x] Comparar c/ versão atual
  - [x] Criar pasta da atualização
  - [x] Baixar arquivo ZIP
  - [x] Descompactar zip para pasta da atualização
  - [x] Transferir arquivos
  - [x] Exibir changelog
  - [x] Executar nova versão (.EXE)
  - [x] Opção ver changelog antes de atualizar

**Comment by facebotgit** [comment]
Feito
